name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: E.g. "The generated code did not compile because xyz..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Numbered steps help a lot.
      placeholder: |
          1. Command or code snippet
          2. Input/record used
          3. Observed output or compiler error
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Advanced Record Utils are you using?
      options:
        - 0.6.1 (Latest)
        - 0.5.1 (Edge)
        - Other/Not listed
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: E.g. "passing null should work"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "`@Generated` annotation"
      description: Found above the created method or class (if applicable).
      placeholder: |
        @Generated(
            value = {"io.github.cbarlin.aru.core.AdvRecUtilsProcessor", "io.github.cbarlin.aru.impl.builder.collection.AddAdder"},
            comments = "Related component claim: builderAdd"
        )
      render: java
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
