= Meta-annotations

You can also use meta-annotations to define a group of settings to apply to a number of disparate records/interfaces. Like the normal annotation, these settings cascade (see above for details), and like the normal annotation the settings it defines get "merged" with others. The order of preference for the merge is:

. Settings on the record itself
. Settings inherited via meta-annotations
. Settings inherited from the package
. Settings inherited from the meta-annotation's package

WARNING: Meta-annotations only apply within one compilation unit (e.g. Maven module). They do not work across compilation boundaries.

With the following example:

NOTE: The settings listed here are explained in detail later in this documentation.

.package-info.java
[source,java]
----
@AdvancedRecordUtils(
    merger = true,
    applyToAllInPackage = true,
    builderOptions = @AdvancedRecordUtils.BuilderOptions(
        buildMethodName = "make"
    )
)
package org.example;

import io.github.cbarlin.aru.annotations.AdvancedRecordUtils;
----

.GenerateDiff.java
[source,java]
----
@io.github.cbarlin.aru.annotations.AdvancedRecordUtils(
    diffable = true,
    builderOptions = @AdvancedRecordUtils.BuilderOptions(
        buildMethodName = "be"
    )
)
public @interface GenerateDiff {}
----

.Person.java
[source,java]
----
package org.example;
public record Person(String name, int age, List<String> favouriteColours) {}
----

.Address.java
[source,java]
----
package org.example;
@GenerateDiff
@AdvancedRecordUtils(
    builderOptions = @AdvancedRecordUtils.BuilderOptions(
        buildMethodName = "make"
    )
)
public record Address(String country, String state) {}
----

.Video.java
[source,java]
----
package org.example;
@GenerateDiff
public record Video(String name, int uploadYear) {}
----

Then that is the equivalent of doing the following without the `+package-info.java+` or the `+GenerateDiff+` annotation:

.Person.java
[source,java]
----
@AdvancedRecordUtils(
    merger = true,
    builderOptions = @AdvancedRecordUtils.BuilderOptions(
        buildMethodName = "make"
    )
)
public record Person(String name, int age, List<String> favouriteColours) {}
----

.Address.java
[source,java]
----
@AdvancedRecordUtils(
    merger = true,
    diffable = true,
    builderOptions = @AdvancedRecordUtils.BuilderOptions(
        buildMethodName = "make"
    )
)
public record Address(String country, String state) {}
----

.Video.java
[source,java]
----
@AdvancedRecordUtils(
    merger = true,
    diffable = true,
    builderOptions = @AdvancedRecordUtils.BuilderOptions(
        buildMethodName = "be"
    )
)
public record Video(String name, int uploadYear) {}
----

TIP: There is an https://github.com/cbarlin/advanced-record-utils/blob/main/advanced-record-utils-annotations/src/main/java/io/github/cbarlin/aru/annotations/AdvancedRecordUtilsFull.java[`+@AdvancedRecordUtilsFull+`] which acts similarly to this (except that it is known to the processor ahead-of-time), and has most optional settings turned on.
