==== Wither

NOTE: The `+With+` and `+All+` interfaces are generated by default. See further down for details on these settings.

To use `+with+` methods (methods that create a new copy of the record with a field changed), you can implement the `+*Utils.All+` interface that's generated for you.

[source,java]
----
@AdvancedRecordUtils
public record Person(String name, int age, List<String> favouriteColours) implements PersonUtils.All { }
----

TIP: Implementing the `+All+` interface is preferable to implementing the `+With+` interface directly because if you enable more utilities they'll be immediately available.

And now you can use `+with+` style methods!

[source,java]
----
// personA and personB defined earlier
Person aButDifferentAge = personA.withAge(42); // Obtains a copy that has the `age` set to 42

PersonUtils.Builder backToBuilder = personB.with(); // Returns a builder instance that is pre-populated with the current values

Person aViaBuilder = personA.with(builder -> builder.name("Connie")); // Fluent use of the builder, allowing for multiple changes to be made easily
----

The `+with+` methods generated broadly align with the same methods generated on the `+Builder+`. For example, if the builder has `+add+` methods enabled on collections (like `+addFavouriteColours+`) then the wither will have an `+add+` method as well (`+withAddFavouriteColours+`)