= XML

The XML utility allows you to serialise a record to XML. At the moment, only serialisation is supported.

WARNING: Using this utility requires you to have `+jakarta.xml.bind-api+` on the classpath as you will need to use the annotations from that library to control the output.

To enable the generation of an `+XML+` interface, enable the `+xmlable+` setting and mark your record fields with the required annotations. To use, implement the `+All+` (or `+XML+`) interface like so:

[source,java]
----
@AdvancedRecordUtils(xmlable = true)
public record Person(
    @XmlElement(name = "Name")
    String name,
    @XmlAttribute(name = "Age")
    int age,
    @XmlTransient
    List<String> favouriteColours
) implements PersonUtils.All {
}
----

TIP: One of the settings later on will give you the option to have the `XmlElement` annotation "inferred" for you so you don't have to annotate your fields

include::../generated-code/usage/xml.adoc[]

And then you can convert an instance into XML:

[source,java]
----
// You will need to handle the XMLStreamException that can be thrown in this example
final XMLStreamWriter streamWriter = createXmlWriter();
streamWriter.writeStartDocument();
// personA from earlier example
personA.writeSelfTo(streamWriter);
streamWriter.writeEndDocument();
----

There are multiple `+writeSelfTo+` methods generated:

* One that takes just the output
* One that takes the output and an override for the tag name
* One that takes the output, an override for the tag name, and an override for the namespace
* One that takes the output, and overrides for the tag name, the namespace, and the current default namespace

The processor calculates the defaults based on the available annotations (such as `+XmlType+`), before finally defaulting to the name of the record (in this case, `+Person+`).