name: GitHub Pages Publish
on:
  # TODO: Remove me once the PR that adds docs is merged
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.3.0
        with:
          asciidoctor_params: --attribute=nofooter
          source_dir: docs/
